	# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ProjectF.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(755, 658)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(185, 185, 185);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Titulo = QtWidgets.QLabel(self.centralwidget)
        self.Titulo.setGeometry(QtCore.QRect(350, 0, 371, 81))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Titulo.setFont(font)
        self.Titulo.setObjectName("Titulo")
        self.Datos_X = QtWidgets.QLabel(self.centralwidget)
        self.Datos_X.setGeometry(QtCore.QRect(30, 170, 61, 21))
        self.Datos_X.setObjectName("Datos_X")
        self.Datos_Y = QtWidgets.QLabel(self.centralwidget)
        self.Datos_Y.setGeometry(QtCore.QRect(30, 210, 61, 21))
        self.Datos_Y.setObjectName("Datos_Y")
        self.DigDatX = QtWidgets.QTextEdit(self.centralwidget)
        self.DigDatX.setGeometry(QtCore.QRect(100, 160, 101, 31))
        self.DigDatX.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.DigDatX.setObjectName("DigDatX")
        self.DigDatY = QtWidgets.QTextEdit(self.centralwidget)
        self.DigDatY.setGeometry(QtCore.QRect(100, 200, 101, 31))
        self.DigDatY.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.DigDatY.setObjectName("DigDatY")
        self.Escudo = QtWidgets.QLabel(self.centralwidget)
        self.Escudo.setGeometry(QtCore.QRect(20, 0, 301, 131))
        self.Escudo.setStyleSheet("border-image: url(:/cct/Escudo UNAL.png);")
        self.Escudo.setText("")
        self.Escudo.setObjectName("Escudo")
        self.Next = QtWidgets.QPushButton(self.centralwidget)
        self.Next.setGeometry(QtCore.QRect(100, 250, 101, 31))
        self.Next.setObjectName("Next")
        self.Polinomio = QtWidgets.QCheckBox(self.centralwidget)
        self.Polinomio.setGeometry(QtCore.QRect(430, 450, 191, 17))
        self.Polinomio.setObjectName("Polinomio")
        self.Lista = QtWidgets.QCheckBox(self.centralwidget)
        self.Lista.setGeometry(QtCore.QRect(30, 450, 151, 17))
        self.Lista.setObjectName("Lista")
        self.ListDat = QtWidgets.QTextEdit(self.centralwidget)
        self.ListDat.setGeometry(QtCore.QRect(60, 470, 271, 51))
        self.ListDat.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ListDat.setObjectName("ListDat")
        self.Import = QtWidgets.QPushButton(self.centralwidget)
        self.Import.setGeometry(QtCore.QRect(410, 110, 191, 41))
        self.Import.setObjectName("Import")
        self.ComboX = QtWidgets.QComboBox(self.centralwidget)
        self.ComboX.setGeometry(QtCore.QRect(560, 160, 121, 31))
        self.ComboX.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ComboX.setObjectName("ComboX")
        self.ComboY = QtWidgets.QComboBox(self.centralwidget)
        self.ComboY.setGeometry(QtCore.QRect(560, 200, 121, 31))
        self.ComboY.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ComboY.setObjectName("ComboY")
        self.Limpiar = QtWidgets.QPushButton(self.centralwidget)
        self.Limpiar.setGeometry(QtCore.QRect(600, 590, 141, 41))
        self.Limpiar.setObjectName("Limpiar")
        self.ComboH = QtWidgets.QComboBox(self.centralwidget)
        self.ComboH.setGeometry(QtCore.QRect(330, 190, 121, 31))
        self.ComboH.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ComboH.setObjectName("ComboH")
        self.Datos_Y_2 = QtWidgets.QLabel(self.centralwidget)
        self.Datos_Y_2.setGeometry(QtCore.QRect(490, 210, 61, 21))
        self.Datos_Y_2.setObjectName("Datos_Y_2")
        self.Datos_X_2 = QtWidgets.QLabel(self.centralwidget)
        self.Datos_X_2.setGeometry(QtCore.QRect(490, 170, 61, 21))
        self.Datos_X_2.setObjectName("Datos_X_2")
        self.Hoja = QtWidgets.QLabel(self.centralwidget)
        self.Hoja.setGeometry(QtCore.QRect(330, 170, 81, 21))
        self.Hoja.setObjectName("Hoja")
        self.Polinomio_2 = QtWidgets.QLabel(self.centralwidget)
        self.Polinomio_2.setGeometry(QtCore.QRect(430, 370, 71, 21))
        self.Polinomio_2.setObjectName("Polinomio_2")
        self.Evaluacion = QtWidgets.QLabel(self.centralwidget)
        self.Evaluacion.setGeometry(QtCore.QRect(30, 370, 81, 21))
        self.Evaluacion.setObjectName("Evaluacion")
        self.Calcular = QtWidgets.QPushButton(self.centralwidget)
        self.Calcular.setGeometry(QtCore.QRect(490, 290, 141, 51))
        self.Calcular.setObjectName("Calcular")
        self.Mos_Evaluacion = QtWidgets.QTextEdit(self.centralwidget)
        self.Mos_Evaluacion.setGeometry(QtCore.QRect(30, 390, 301, 31))
        self.Mos_Evaluacion.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Mos_Evaluacion.setObjectName("Mos_Evaluacion")
        self.Mos_Polinomio = QtWidgets.QTextEdit(self.centralwidget)
        self.Mos_Polinomio.setGeometry(QtCore.QRect(430, 390, 301, 31))
        self.Mos_Polinomio.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Mos_Polinomio.setObjectName("Mos_Polinomio")
        self.DigDatY_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.DigDatY_2.setGeometry(QtCore.QRect(330, 300, 101, 31))
        self.DigDatY_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.DigDatY_2.setObjectName("DigDatY_2")
        self.P_evaluar = QtWidgets.QLabel(self.centralwidget)
        self.P_evaluar.setGeometry(QtCore.QRect(240, 310, 81, 21))
        self.P_evaluar.setObjectName("P_evaluar")
        self.Grafica_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Grafica_2.setGeometry(QtCore.QRect(30, 540, 111, 31))
        self.Grafica_2.setObjectName("Grafica_2")
        self.XS = QtWidgets.QLabel(self.centralwidget)
        self.XS.setGeometry(QtCore.QRect(30, 470, 31, 16))
        self.XS.setObjectName("XS")
        self.YS = QtWidgets.QLabel(self.centralwidget)
        self.YS.setGeometry(QtCore.QRect(30, 490, 31, 16))
        self.YS.setObjectName("YS")
        self.Poliexp = QtWidgets.QTextEdit(self.centralwidget)
        self.Poliexp.setGeometry(QtCore.QRect(430, 470, 301, 51))
        self.Poliexp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Poliexp.setObjectName("Poliexp")
        self.Escudo.raise_()
        self.YS.raise_()
        self.XS.raise_()
        self.Titulo.raise_()
        self.Datos_X.raise_()
        self.Datos_Y.raise_()
        self.DigDatX.raise_()
        self.DigDatY.raise_()
        self.Next.raise_()
        self.Polinomio.raise_()
        self.Lista.raise_()
        self.ListDat.raise_()
        self.Import.raise_()
        self.ComboX.raise_()
        self.ComboY.raise_()
        self.Limpiar.raise_()
        self.Datos_Y_2.raise_()
        self.Datos_X_2.raise_()
        self.Hoja.raise_()
        self.Polinomio_2.raise_()
        self.Evaluacion.raise_()
        self.Calcular.raise_()
        self.Mos_Evaluacion.raise_()
        self.Mos_Polinomio.raise_()
        self.P_evaluar.raise_()
        self.ComboH.raise_()
        self.DigDatY_2.raise_()
        self.Grafica_2.raise_()
        self.Poliexp.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 755, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.DigDatX, self.DigDatY)
        MainWindow.setTabOrder(self.DigDatY, self.Next)
        MainWindow.setTabOrder(self.Next, self.DigDatY_2)
        MainWindow.setTabOrder(self.DigDatY_2, self.Calcular)
        MainWindow.setTabOrder(self.Calcular, self.Mos_Evaluacion)
        MainWindow.setTabOrder(self.Mos_Evaluacion, self.Mos_Polinomio)
        MainWindow.setTabOrder(self.Mos_Polinomio, self.Lista)
        MainWindow.setTabOrder(self.Lista, self.ListDat)
        MainWindow.setTabOrder(self.ListDat, self.Polinomio)
        MainWindow.setTabOrder(self.Polinomio, self.Poliexp)
        MainWindow.setTabOrder(self.Poliexp, self.Grafica_2)
        MainWindow.setTabOrder(self.Grafica_2, self.Limpiar)
        MainWindow.setTabOrder(self.Limpiar, self.ComboH)
        MainWindow.setTabOrder(self.ComboH, self.Import)
        MainWindow.setTabOrder(self.Import, self.ComboY)
        MainWindow.setTabOrder(self.ComboY, self.ComboX)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Titulo.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-style:normal; color:#f50e0e;\">Polinomio Interpolador de Lagrange</span></p></body></html>"))
        self.Datos_X.setText(_translate("MainWindow", "Datos en X"))
        self.Datos_Y.setText(_translate("MainWindow", "Datos en Y"))
        self.Next.setText(_translate("MainWindow", "Siguiente Valor"))
        self.Polinomio.setText(_translate("MainWindow", "Ver polinomio expandido"))
        self.Lista.setText(_translate("MainWindow", "Ver lista de datos"))
        self.Import.setText(_translate("MainWindow", "Importar archivo"))
        self.Limpiar.setText(_translate("MainWindow", "Limpiar"))
        self.Datos_Y_2.setText(_translate("MainWindow", "Datos en Y"))
        self.Datos_X_2.setText(_translate("MainWindow", "Datos en X"))
        self.Hoja.setText(_translate("MainWindow", "Hoja del archivo"))
        self.Polinomio_2.setText(_translate("MainWindow", "Polinomio"))
        self.Evaluacion.setText(_translate("MainWindow", "Evaluación"))
        self.Calcular.setText(_translate("MainWindow", "Calcular"))
        self.P_evaluar.setText(_translate("MainWindow", "Punto a evaluar"))
        self.Grafica_2.setText(_translate("MainWindow", "Ver Gráfica"))
        self.XS.setText(_translate("MainWindow", " X ="))
        self.YS.setText(_translate("MainWindow", " Y ="))
import Escudo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
