# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Segunda.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Segunda(object):
    def setupUi(self, Segunda):
        Segunda.setObjectName("Segunda")
        Segunda.resize(316, 124)
        Segunda.setStyleSheet("background-color: rgb(185, 185, 185);")
        self.centralwidget = QtWidgets.QWidget(Segunda)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(40, 10, 251, 51))
        self.textEdit.setObjectName("textEdit")
        Segunda.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Segunda)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 316, 22))
        self.menubar.setObjectName("menubar")
        Segunda.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Segunda)
        self.statusbar.setObjectName("statusbar")
        Segunda.setStatusBar(self.statusbar)

        self.retranslateUi(Segunda)
        QtCore.QMetaObject.connectSlotsByName(Segunda)

    def retranslateUi(self, Segunda):
        _translate = QtCore.QCoreApplication.translate
        Segunda.setWindowTitle(_translate("Segunda", "MainWindow"))
        self.textEdit.setHtml(_translate("Segunda", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ha digitado una letra, por favor digite un número</p></body></html>"))
